import type { LineIconName } from "@/components/cards/LineIcon";

/**
 * エディタでアイコンを選択するときの一覧（自由入力禁止・LineIcon と一致）
 */
export const LINE_ICON_EDITOR_OPTIONS: { value: LineIconName; label: string }[] = [
  { value: "wifi", label: "Wi‑Fi" },
  { value: "breakfast", label: "朝食" },
  { value: "utensils", label: "食事（カトラリー）" },
  { value: "checkout", label: "チェックアウト" },
  { value: "clock", label: "時計・時間" },
  { value: "restaurant", label: "レストラン" },
  { value: "spa", label: "スパ・温泉" },
  { value: "bath", label: "お風呂" },
  { value: "parking", label: "駐車場" },
  { value: "car", label: "車" },
  { value: "map", label: "地図" },
  { value: "map-pin", label: "ピン" },
  { value: "nearby", label: "周辺" },
  { value: "notice", label: "お知らせ" },
  { value: "bell", label: "ベル" },
  { value: "emergency", label: "緊急" },
  { value: "phone", label: "電話" },
  { value: "laundry", label: "ランドリー" },
  { value: "washing-machine", label: "洗濯機" },
  { value: "taxi", label: "タクシー" },
  { value: "train", label: "電車" },
  { value: "bus", label: "バス" },
  { value: "credit-card", label: "カード" },
  { value: "key", label: "鍵" },
  { value: "toothbrush", label: "歯ブラシ" },
  { value: "hanger", label: "ハンガー" },
  { value: "broom", label: "掃除" },
  { value: "microwave", label: "電子レンジ" },
  { value: "package", label: "荷物" },
  { value: "bed", label: "ベッド" },
  { value: "ticket", label: "チケット" },
  { value: "info", label: "情報（i）" },
  { value: "link", label: "リンク" },
  { value: "language", label: "言語" },
  { value: "coffee", label: "コーヒー" },
  { value: "shopping-bag", label: "買い物袋" },
  { value: "camera", label: "カメラ" },
  { value: "gift", label: "ギフト" },
  { value: "baby", label: "ベビー" },
  { value: "shield", label: "シールド" },
  { value: "check", label: "チェック" },
  { value: "quote", label: "引用" },
  { value: "checklist", label: "チェックリスト" },
  { value: "steps", label: "ステップ" },
  { value: "compare", label: "比較" },
  { value: "kpi", label: "KPI・数値" },
];
